### ISSUE TITLE
some question about paper

### ISSUE THREAD

**Issue by LiuXD1011** [postech-ami/Deep-Motion-Mag-Pytorch#1]
Thank you for your great work, which has been of great help to me. When I was reading a paper, I came across a part that said 'approximate our (non-linear) spatial encoder as linear convolution kernels', but I couldn't understand how this is done. Do you have any ideas?
![图片](https://github.com/user-attachments/assets/4c3edecb-4131-4862-bd68-caae23967c6b)

**Comment by Byungki-Kwon** [comment]
Professor Tae-Hyun Oh, the author of this paper, has provided a response at the following link. Please refer to it.

https://github.com/12dmodel/deep_motion_mag/issues/24

**Comment by LiuXD1011** [comment]
Thanks for your reply!
